development:
  paypal_email: "ronanclarke-facilitator@gmail.com"
  paypal_secret: foobar
  paypal_cert_id: "S796CLEQL9EM8"
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"


test:
  paypal_email: "ronanclarke-facilitator@gmail.com"
  paypal_secret: testsecret
  paypal_cert_id: 123456789
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

staging:
  paypal_email: ronanclarke@gmail.com
  paypal_secret: supersecret
  paypal_cert_id: "VTFCMMC9ATLSL"
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"

production:
  paypal_email: ronanclarke@gmail.com
  paypal_secret: supersecret
  paypal_cert_id: "VTFCMMC9ATLSL"
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"